# -*- coding: utf-8 -*-
"""CSE390-Spring2024-HW3.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14YykT2ErYHvpjEWihMJX9Vy-nseCWSU7

# Preface: Google Colab

For this assignment, we will use Google Colab. This will allow us to use resources like GPUs that may not be available on our personal computers, and ensure identical use of external dependencies for everybody. You can use your Stony Brook (`*.stonybrook.edu`) account and save the results on Google Drive.

To get started, go to the [Google Colab Notebook](https://colab.research.google.com/notebooks/). There, you'll find a tutorial called *Overview of Colaboratory Features*, which provides a quick overview on using Google Colab. There is also this concise [Google Colab Tutorial](https://colab.research.google.com/drive/16pBJQePbqkz3QFV54L4NIkOn1kwpuRrj).

Colab is built on top of Jupyter notebook. But remember, inactivity will disconnect your runtime environment.

## Libraries

You are encouraged to use the following libraries as and when needed. This assignment is as much about learning to use available tools, as it is about understanding how to implement simple aspects of computational finance.

- **NumPy**: the most important library for numerical computations in Python; provides support for arrays and matrices; has a large collection of high-level mathematical functions used in linear algebra and probability/statistics.
- **Pandas**: for high-performance, easy-to-use data structures and data analysis; particularly good for data manipulation and analysis; offers `DataFrame` objects, which are ideal for time-series data.
- **SciPy** or **PyTorch**: for optimization, regression, interpolation, etc.
- **Statsmodels**: statistical modeling library built on top of NumPy and SciPy.
- **Matplotlib** and **Seaborn**: for plotting and visualization.

# American Put Options (20 points)

Write your solution to the first question (**American Put Options**) in the cell below. You are free to have additional methods, but the user should be able to call only the `price_american_put_options` function to obtain the results corresponding to each line in the input text or file.
"""

def price_american_put_options(input_text: str | bytes) -> None:
    """
    Processes American put option parameters from a multi-line string or from a text file containing such data.

    This function expects each line to contain tab-separated values with the following parameters:
    risk_free_rate, time in years, number of steps, volatility, initial price, and strike price. It computes and prints
    the value (one per line) of the American put option for each line of input.

    Parameters:
    - input_data (str | bytes): A multi-line string with tab-separated values or a path to a text file containing such
                                data.

    Note:
    - The function directly prints (one output per line) the calculated option prices, hence no return value.
    """
    pass  # TODO

def value_of_american_put_option(risk_free_rate: float, time: float, num_steps: int, volatility: float,
                                 initial_price: float, strike_price: float) -> float:
    """
    Calculates the value of an American put option using the Binomial Tree model.

    Parameters:
    - risk_free_rate (float): The risk-free interest rate (annualized).
    - time (float): Time to expiration of the option (in years).
    - num_steps (int): Number of steps in the binomial model.
    - volatility (float): Annual volatility of the underlying asset.
    - initial_price (float): The initial stock price.
    - strike_price (float): The strike price of the option.

    Returns:
    - float: The estimated value of the American put option.

    notes:
    - uses risk-neutral probability p = (e^{r dt} - d) / (u - d), with u = e^{sigma sqrt(dt)}, d = 1/u.
    - handles degenerate cases (e.g., sigma ≈ 0 or dt ≈ 0) by falling back to intrinsic/discounted payoff logic.
    """


    return 0.0  # TODO

"""# Asian Call Options (20 points)

Write your solution to the second question (**Asian Call Options**) in the cell below. You are free create additional functions, but the user must be able to call `price_asian_call_options` to obtain the results corresponding to each line in the input text or file.
"""

def price_asian_call_options(input_text: str | bytes) -> None:
    """
    Processes Asian call option parameters from a multi-line string or from a text file containing such data.

    This function expects each line to contain tab-separated values with the following parameters:
    risk_free_rate, time in years, number of steps, volatility, initial price, and strike price. It computes and prints
    the value (one per line) of the Asian call option for each line of input.

    Parameters:
    - input_data (str | bytes): A multi-line string with tab-separated values or a path to a text file containing such
                                data.

    Note:
    - The function directly prints (one output per line) the calculated option prices, hence no return value.
    """
    pass  # TODO

"""# Linear Time Series Models

Start by completing the `README` section below, which should provide a precise explanation of how to run your code on the given data (including providing the input tab-separated file).

**Note 1:** At no point should the user/grader need to change anything in your code. For example, the input file should not be hard-coded in your program!

**Note 2:** Your `README` should very clearly mention exactly which function the user should call, and how the user should provide the tab-separated file as input.

**Note 3:** Your implementation must be supported by proper documentation in the form of docstrings, as shown in earlier cells where the function signatures were already provided. (**5 points**)

### README (5 points)

*TODO*

### AR($p$) and MA($q$) implementation (20 points)
"""

# TODO: Your AR and MA model implementations go here

"""### ACF and PACF visualization (10 points)"""

# TODO: write the code to generate two plots (one for ACF and one for PACF).

"""### The Simple Autoregressive Model AR($p$) (10 points)

- TODO: clearly state your choice of $p$
- TODO: clearly state your estimated parameter values (for the sake of easier interpretaion, please use the same symbols we have used in our lectures)
- TODO: How did you arrive at this choice of $p$? Provide a precise description of your process and a brief justification.

### The Moving Average Model MA($q$) (10 points)

- TODO: clearly state your choice of $q$
- TODO: clearly state your estimated parameter values (for the sake of easier interpretaion, please use the same symbols we have used in our lectures)
- TODO: How did you arrive at this choice of $q$? Provide a precise description of your process and a brief justification.

# Collaboration and Resource Use Policy

You may discuss any details of this assignment at a conceptual level with anyone. In fact, discussion of ideas and helping each other to gain a better understanding of the concepts and the mathematical principles is encouraged. But any written answers (natural language or programming language) must be entirely your own original work.

You are also encouraged to use the libraries mentioned at the start of this notebook. The use of online resources (e.g., StackOverflow) that can help you understand specific functions in these libraries is also encouraged.

There must not be any collaboration in programming (including the design, implementation, and debugging of code). There must not be any code in your submission that is written by anyone other than you (whether human or AI). Submitted code will be checked against other submissions AND against AI-generated code, and evidence of plagiarism will lead to academic dishonesty charges.

# What to submit?

**This assignment is due by 11:59 pm, APR 30 (Tuesday)**

1. Make your colab notebook publicly accessible. You can do this by clicking "Share" on the top-right corner of your notebook and make sure "anyone with the link" can view your notebook. Also make sure that viewers are allowed to download your notebook. Then, **put this link in the comment section of your submission on Brightspace**.

2. Create an empty folder (locally, on your computer) called `firstname-lastname-cse390-hw3`. For example, John Doe will create `john-doe-cse354-hw3`.
    * Download this colab notebook with all the questions (code as well as the text questions) implemented/answered. This will be a single Python notebook, as a `.ipynb` file. Put the notebook in your folder.
    
    Zip this folder (i.e., create `firstname-lastname-cse390-hw3.zip`) and submit on Brightspace.

Once unzipped, your submission is expected to have the following structure:

```
john-doe-cse390-hw4
└── CSE390-Spring2024-HW4.ipynb
```
"""